# Generated by Django 4.2.14 on 2026-08-20 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0003_alter_study_material_uploaded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study_material',
            name='Uploaded_date',
            field=models.DateField(default=datetime.date(2026, 8, 20)),
        ),
    ]
